modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/LoTek2012/AstraLib/issues/new"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/LoTek2012/AstraLib/refs/heads/main/updates.json"
displayURL="https://github.com/LoTek2012/AstraCraft"
authors="Loan"
description='''
A library for Minecraft space mods used in AstraCraft
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="astralib"
    type="required"
    versionRange="${[1.0.0]}"
    ordering="NONE"
    side="BOTH"
